name: First Workflow
on: workflow_dispatch # trigger
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Phuc!"
      - name: Print goodbye
        run: echo "Goodbye!"
